### ISSUE TITLE
Semantic segmentation results for camvid dataset in your paper

### ISSUE THREAD

**Issue by chowkamlee81** [varunjampani/video_prop_networks#4]
Do you have any scripts to work on semantic segmentation using video propgation networks?
Kindly provide  which would be helpful

**Comment by varunjampani** [comment]
Currently, we do not have any plan to release the scripts for semantic segmentation. The scripts for these are quite similar to those for 'object segmentation' and 'color propagation' which are already released. Let me know if you have any specific questions. I will look into releasing some scripts for semantic segmentation when I find some time.
