### ISSUE TITLE
How could i retrain the color_propagation model

### ISSUE THREAD

**Issue by youyingyin** [varunjampani/video_prop_networks#6]
Hi, thank you for sharing. How could i retrain the color_propagation model?

**Comment by varunjampani** [comment]
Sorry, we do not have time to release the training scripts for color_propagation. You can check the testing scripts for 'color_propagation' and modify the training scripts in 'seg_propagation' accordingly.

**Comment by youyingyin** [comment]
> Sorry, we do not have time to release the training scripts for color_propagation. You can check the testing scripts for 'color_propagation' and modify the training scripts in 'seg_propagation' accordingly.

thanks for your reply
